coco:
  max-customer-per-service: 2
  welcome: Welcome! Any questions?
  auto-reply-after-work: Sorry, we are all off, you can leave your questions and we will respond to you.
  unified-service-name: Great Company
  always-display-unified-service-name: true